### ISSUE TITLE
docker 能正常启动但是请求报错

### ISSUE THREAD

**Issue by liwc0329** [Mereithhh/chatgpt-session-server#1]

**Comment by liwc0329** [comment]
server start！
[request] { username: 'xxxx@hotmail.com', password: 'JYq4TY62' }
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator('h1') to be visible
============================================================
    at getToken (file:///app/server.js:35:14)
    at Server.<anonymous> (file:///app/server.js:113:21) {
  name: 'TimeoutError'
}
server start！
[request] { username: 'linwahapersw@hotmail.com', password: 'JYq4TY62' }
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator('h1') to be visible
  locator resolved to visible <h1 aria-label="ChatGPT by OpenAI">…</h1>
============================================================
    at getToken (file:///app/server.js:35:14)
    at Server.<anonymous> (file:///app/server.js:113:21) {
  name: 'TimeoutError'
}
server start！
